"""Chapters 7-9: roles, company-wide rules, incentive plan."""
from kit import P, H1, H2, H3, B, T, Callout, Flow, TEAL, RED, ACCENT, GREEN


def role(name, src, mission, owns, rhythm, decide, kpis, day1, extra=None):
    out = [*H2(name), P(f"<i>“{mission}”</i> {src}")]
    out += [H3("Owns / does"), *B(owns)]
    out += [H3("Rhythm"), *T([["When", "What"]] + rhythm, [0.14, 0.86])]
    if extra:
        out += extra
    out += [H3("Decides vs. escalates"), *T([["Situation", "Who decides"]] + decide, [0.6, 0.4])]
    out += [H3("Measured on"), *T([["KPI", "Measured via", "Reviewed"]] + kpis, [0.5, 0.32, 0.18])]
    out += [H3("Day 1 checklist"), *B(day1)]
    return out


def ch_roles():
    return [
        *H1("Roles in Detail", "Chapter 7",
            "Everything each role brief says, in the same order for every role. Founder and Creative Head duties come from the Handbook "
            "and the 'escalate to' columns of the other briefs."),

        *H2("Founder (Zameel)"),
        *B(["Sells: owns the monthly sales target of 47 engagements / ₹3,53,500 [Incentive]. The CRM receives 'Sales handover notes' from them.",
            "Decides: pricing, packages, discounts, new deliverables, deadline changes promised to clients, scope changes, refunds and contract disputes [CRM].",
            "Receives escalations: client threatens to cancel or demands a refund; payment unresolved after one follow-up; team wellbeing or reputation risk [CRM].",
            "People: approves discipline warnings, owns HR policy, final call on hiring [HR][Handbook §05].",
            "Reviews the Creative Head's 13-category monthly scorecard [Handbook §45]."]),

        *H2("Creative Head"),
        P("<i>“I own the health and performance of the overall creative department — the strength of its Team Leaders, the productivity, quality and "
          "accountability of every team, and the systems that let it grow without breaking.”</i> [Handbook §03]"),
        *B(["Sits above the Logo TL, Packaging TL, R&D, the Sketch Artist and the Internal Content Team. Promoted from Logo Team Leader after turning that team around.",
            "Is <b>not</b> a bigger Team Leader, not a designer, and not a client manager. The job is making Team Leaders better.",
            "Receives escalations (L3 in the TL briefs): client-facing deadline at risk, the same designer's quality issue recurring 2+ times, whole team overloaded, "
            "R&D queue overload, unclear R&D direction reported by the Sketch Artist.",
            "Approves: P1 urgent R&D projects, missed client deadlines, extra unpaid revisions (together with the Founder).",
            "Runs: the daily leadership check-in, the weekly Team Leader review (8 questions), the monthly department review. Full system in Chapter 10."]),

        *role("Client Relationship Manager (CRM)", "[CRM]",
              "You are the single bridge between the client and the production team … You catch unclear requirements before they cost the team a redo, and you catch scope creep before anyone agrees to it.",
              ["Client onboarding and welcome communication",
               "Client meetings: requirement collection and briefing; collecting references, brand materials and files",
               "Clarifying requirements before they reach R&D",
               "Sending updates and submissions to clients; following up for approvals and final sign-off",
               "Collecting feedback and forwarding it internally in a structured way; coordinating corrections",
               "Maintaining the Client Database; first-level complaint handling",
               "Per Incentive: collects payments (50/50) and 'closes deals'; pushes both TLs to keep projects moving"],
              [["Daily", "Check the Client Meetings WhatsApp group. Respond to open threads within SLA. Update the Project Tracker on any status change. Log new feedback."],
               ["Weekly", "Review every active client for pending approvals or stalled threads. Flag anything unresolved for 3+ days to the Creative Head."],
               ["Monthly", "Summarise client satisfaction signals (delays, complaints, praise) for the monthly review."]],
              [["Accept a clearly in-scope correction", "CRM decides"],
               ["Tone and cadence of client communication", "CRM decides"],
               ["Promise a new deliverable, discount or deadline change", "Escalate to Founder/Sales"],
               ["Anything that looks like a scope change", "Escalate before agreeing"],
               ["Authorise a designer to speak to a client", "CRM's call, but log the exception"]],
              [["Client response-time SLA adherence", "Project Tracker timestamps", "Weekly"],
               ["Approval turnaround time", "Project Tracker timestamps", "Weekly"],
               ["(Bonus) projects cleanly closed + paid on time", "TL completion logs + payment records", "Monthly"]],
              ["Get access to the Client Database, Project Tracker and both WhatsApp groups (Leads, Client Meetings)",
               "Log every active client's real status today; pick up mid-handover clients from Sales first",
               "Send a status update to any client silent for 3+ days"],
              extra=[H3("Onboarding checklist (7 steps)"),
                     *B(["Review Sales handover notes (package sold, price, promises made)", "Add client to the Client Database",
                         "Send welcome message confirming package, price and next step", "Schedule the client meeting; post it to the Client Meetings group",
                         "Run a structured discovery call (brand story, references, must-haves / must-avoids)",
                         "Collect materials (logos, photos, references) into the Drive project folder", "Hand the completed Project Brief to R&D with a priority"])]),

        *role("R&D (Research & Creative Direction)", "[R&D]",
              "Every logo and packaging project in Brandstro starts with you … your output is the most important single input in the entire production line.",
              ["Industry, competitor and category research", "Target audience and brand positioning research",
               "Visual, symbol and cultural reference research", "A structured research brief, not raw inspiration links",
               "Handing direction to the Sketch Artist (logo) or the Packaging Team (packaging)", "Working ahead on queued projects when capacity allows"],
              [["Daily", "Work the queue in priority order. One structured brief per project. Log the handoff in the Project Tracker the moment it's done."],
               ["Weekly", "Report queue length and flag at-risk projects to the Creative Head before they become missed deadlines."]],
              [["Re-order same-priority projects for efficiency", "R&D decides"], ["Depth and direction of research", "R&D decides"],
               ["Deprioritise a Founder/CRM-flagged urgent project", "Needs Creative Head approval"],
               ["Queue consistently overloaded", "Flag to Creative Head (don't silently work longer)"],
               ["Brief from CRM is unclear", "Flag back to CRM before researching on an assumption"],
               ["A P1 lands", "Drop everything; others queue behind it"]],
              [["Briefs delivered on time", "Project Tracker", "Weekly"], ["Briefs requiring rework", "Team Leader feedback", "Weekly"],
               ["(Bonus) concepts beyond baseline, by downstream revision tier", "Project Tracker", "Monthly"]],
              ["Access to the Project Tracker and Drive folders", "Pull today's queue in payment-confirmed order; spot anything at risk",
               "Use the research brief template from the very next project", "Tell the Creative Head your realistic daily capacity"],
              extra=[H3("Research brief template (every project, every time)"),
                     *B(["Client and business overview", "Target audience", "Competitor / category references (3–5 examples)",
                         "Positioning direction (1–2 sentence recommendation)", "Visual / symbol direction (mood, motifs, cultural references)",
                         "Anything the client explicitly wants included or avoided"]),
                     H3("Queue priority"),
                     *T([["Priority", "Rule"],
                         ["P1 Urgent", "Founder/Creative Head approved. Jumps the queue. <b>Only one P1 active at a time.</b>"],
                         ["P2 Standard", "Normal paid project, worked in the order payment was confirmed (FIFO)."],
                         ["P3 Ahead", "Upcoming project worked while waiting on a dependency. Only when no P1/P2 is ready."]], [0.2, 0.8]),
                     H3("Handoff rule"),
                     *B(["Mark the brief complete in the Project Tracker", "Tag the next owner (Sketch Artist for logo, Packaging Team for packaging)",
                         "Save the brief in the project's Drive folder 02_R&D",
                         "<b>An unacknowledged handoff counts as not yet started.</b> Confirm the next owner has picked it up."])]),

        *role("Sketch Artist", "[Sketch]",
              "You're the bridge between R&D's research and the Logo Team's digital production … you don't need to make it pretty yet, you need to make it right.",
              ["Study the research brief and creative direction",
               "Produce 3–5 <b>distinct</b> sketch concepts per logo project (e.g. wordmark vs symbol vs combination mark, not variations of one idea)",
               "Explain the rationale for each (one line)", "Submit to the Logo Team Leader with the research brief attached",
               "Refine only when the Logo Team or Creative Head asks for a specific direction adjustment",
               "Handoff to the Logo Team completes the Sketch Artist's part. Don't polish sketches into finished art."],
              [["Daily", "Work the sketch queue in priority order; hand off completed sets the same day where possible."],
               ["Weekly", "Report queue length to the Creative Head. Flag any unclear R&D direction before guessing."]],
              [["Which directions to explore within the brief", "Sketch Artist decides"], ["Order of same-priority sketches", "Sketch Artist decides"],
               ["R&D brief unclear or contradictory", "Flag to R&D / Creative Head"], ["Queue consistently overloaded", "Flag to Creative Head early"]],
              [["Concepts delivered on time", "Project Tracker", "Weekly"], ["Concept sets requiring redirection", "Project Tracker", "Weekly"],
               ["(Bonus) % of sketches the Logo Team completes with no rework", "Logo TL records", "Monthly"]],
              ["Access to the Project Tracker and Drive folders", "Pull today's queue; confirm each brief is complete before starting",
               "Apply the 3–5 distinct-directions standard", "Tell the Creative Head your realistic daily capacity"],
              extra=[H3("Quality self-check"),
                     *B(["Concepts are visually distinct from each other", "Concepts trace back to the brief's positioning and visual direction",
                         "Concepts can scale to a clean digital logo (not overly intricate)"])]),

        *role("Logo Team Leader", "[LogoTL]",
              "You lead the Logo Team's output and quality … You manage the system and the people; you're not just the 5th designer.",
              ["Assigning incoming sketch sets and briefs across the designers, <b>by current load in the Team Task Tracker</b>",
               "Monitoring workload and deadlines; supporting designers who are stuck or behind",
               "First-level internal review of <b>every logo, every time</b> (non-negotiable, even under deadline pressure)",
               "Coordinating capacity and escalations with the Creative Head; reporting team status daily and weekly",
               "Enforcing file naming and versioning; own design output (baseline 2 logos/month per Incentive)"],
              [["Daily", "Assign new sketches/briefs. Review designs completed today against the Logo QC checklist. Flag blockers immediately."],
               ["Weekly", "Report team output and recurring quality issues to the Creative Head."]],
              [["Reassign work within the team", "TL decides"], ["Reject a design at review, send for rework", "TL decides"],
               ["Approve a missed client deadline", "Escalate to Creative Head"],
               ["Approve extra unpaid revisions beyond the package", "Escalate to Creative Head / Founder"],
               ["Talk to the client directly", "Needs CRM / Founder authorisation"],
               ["Missed internal deadline", "TL re-sequences; escalate if the client deadline is at risk"],
               ["Quality issue at review", "Send back; escalate if it recurs on the same designer 2+ times"],
               ["Designer overloaded", "Rebalance; escalate if the whole team is overloaded"],
               ["Correction looks like a new direction", "Flag to Creative Head (don't quietly redo)"]],
              [["Team on-time delivery rate", "Project Tracker", "Weekly"], ["First-review pass rate", "QC checklist logs", "Weekly"],
               ["Client revision rounds per project", "Project Tracker", "Weekly"], ["Designer throughput (≈1 logo/day/designer)", "Team Task Tracker", "Weekly"]],
              ["Access to the Project Tracker, Team Task Tracker and Logo QC checklist", "Check load across designers; rebalance backlog today",
               "Confirm every in-progress logo has a version number and correct Drive folder", "Brief the team: nothing goes out without TL sign-off"]),

        *role("Logo Designer", "[LogoDes]",
              "You turn a sketch concept and research direction into a professional, presentation-ready logo. Your craft is the product Brandstro sells.",
              ["Digital development of the assigned concept: typography, colour, composition, refinement",
               "Self-check against the Logo QC checklist before submitting", "Prepare the client-ready presentation mockup",
               "Apply correction rounds as assigned by the TL; finalise and hand off approved files", "Follow file naming and folder conventions exactly"],
              [["Daily (7 steps)", "1 Receive concept + brief from TL → 2 Digital development → 3 Self-QC → 4 Submit to TL → 5 Apply TL feedback → "
                "6 Prepare client mockup → 7 Apply client corrections as assigned; finalise once approved."]],
              [["Typography, colour, composition within the brief", "Designer decides"], ["How to execute an assigned correction", "Designer decides"],
               ["Is client feedback in scope or a new direction?", "Flag to TL (don't guess)"], ["Talking to the client", "Not unless CRM/Founder authorises"],
               ["About to miss a deadline", "Tell the TL early, not at the deadline"]],
              [["On-time rate", "Project Tracker", "Weekly"], ["Revision rounds per project", "Project Tracker", "Weekly"],
               ["First-review pass rate", "QC checklist logs", "Weekly"], ["Throughput (≈1 logo/day)", "Team Task Tracker", "Weekly"]],
              ["Access to the Drive structure and Team Task Tracker", "Confirm current assignments and deadlines with the TL",
               "Use the file naming convention from the next save", "Keep the Logo QC checklist at hand"]),

        *role("Packaging Team Leader", "[PackTL]",
              "Your team covers packaging, labels, and every collateral piece in the Branding Package (visiting card, letterhead, t-shirt, brand guideline book).",
              ["Assigning packaging, label and collateral work across 3 designers by load",
               "Planning a full Branding Package's non-logo set as <b>one coordinated job</b>",
               "First-level review against the Packaging QC / print-readiness checklist, every deliverable, every time",
               "Coordinating capacity and escalations with the Creative Head; daily and weekly status reporting",
               "Own design output (small baseline per Incentive)"],
              [["Daily", "Assign work arriving from R&D or a branding-package brief. Review today's completed work against the QC checklist. Flag blockers."],
               ["Weekly", "Report team output and recurring quality issues to the Creative Head."]],
              [["Reassign within team / reject at review", "TL decides"], ["Approve a missed client deadline", "Escalate to Creative Head"],
               ["Extra unpaid revisions", "Escalate to Creative Head / Founder"], ["Talk to client", "Needs CRM / Founder authorisation"],
               ["Quality/print issue recurs on same designer 2+ times", "Escalate to Creative Head"],
               ["Correction is a new layout direction", "Flag to Creative Head"]],
              [["Team on-time delivery rate", "Project Tracker", "Weekly"], ["First-review pass rate", "QC checklist logs", "Weekly"],
               ["Client revision rounds per project", "Project Tracker", "Weekly"], ["Print-readiness pass rate", "QC checklist logs", "Weekly"],
               ["Designer throughput (≈1 design/day)", "Team Task Tracker", "Weekly"]],
              ["Access to the trackers and Packaging QC checklist", "Rebalance backlog across the 3 designers",
               "Confirm versioning and Drive locations of in-progress pieces", "Brief the team on the review chain"]),

        *role("Packaging Designer", "[PackDes]",
              "Precision matters here more than anywhere else in Brandstro — a print mistake is expensive and hard to undo once approved.",
              ["Study the product, brand direction and R&D output",
               "Develop concepts: layout, typography, colour, information hierarchy",
               "Mockups and print-ready artwork (correct dimensions, bleed, safe area, CMYK, resolution)",
               "Covers packaging, labels, visiting cards, letterheads, t-shirts and brand guideline books",
               "Apply corrections (with a <b>fresh print-readiness check</b> if dimensions, bleed or artwork changed); finalise files"],
              [["Daily (7 steps)", "1 Receive brief → 2 Concept → 3 Mockup + print artwork → 4 Self-check → 5 Submit to TL → 6 Apply TL feedback → "
                "7 Client corrections; finalise print-ready files."]],
              [["Layout, typography, colour within the brief", "Designer decides"], ["Client feedback in scope?", "Flag to TL"],
               ["Talking to the client", "Not unless authorised"], ["About to miss a deadline", "Tell the TL early"]],
              [["On-time rate", "Project Tracker", "Weekly"], ["Revision rounds per project", "Project Tracker", "Weekly"],
               ["Print-readiness pass rate", "QC checklist logs", "Weekly"], ["Throughput (≈1 design/day)", "Team Task Tracker", "Weekly"]],
              ["Access to Drive and the Team Task Tracker", "Confirm assignments and deadlines", "Use the file naming convention",
               "Keep the print-readiness checklist at hand"]),

        *role("HR / Admin", "[HR]",
              "You own people administration — attendance, leave, records, and the smooth running of onboarding and exits … You do not interfere with design or creative decisions.",
              ["Attendance tracking, corrections and leave management", "Employee records and documentation",
               "Basic discipline tracking and escalation to the Founder", "Internal administration and company sheet maintenance",
               "Supporting onboarding and exit processes",
               "Per Incentive (broader): keeps accounts and pushes the CRM and TLs to keep work moving on the Founder's behalf"],
              [["Daily", "Log attendance. Flag unapproved absences the same day."],
               ["Weekly", "Reconcile leave balances. Report discipline issues to the Founder."],
               ["Monthly", "Attendance trend summary for the monthly review. Keep employee documents current."]],
              [["Log attendance and leave per policy", "HR decides"], ["Flag a coverage gap to a TL", "Inform, don't resolve"],
               ["Issue a formal warning", "Founder awareness required first"], ["Change HR policy", "Founder only"],
               ["A design/creative question", "Redirect to Creative Head"], ["Late arrival, first time", "Log; escalate if the pattern repeats"],
               ["Unapproved absence", "Flag same day; inform Founder if it recurs"], ["Employee conflict", "Route to TL first; Founder if unresolved or it involves a TL"]],
              [["Attendance accuracy", "Attendance sheet", "Monthly"], ["Onboarding/exit checklist completion", "Checklist records", "Monthly"],
               ["(Bonus) team members hitting their own target", "Incentive tally", "Monthly"]],
              ["Set up the Attendance/HR sheet and start logging today", "Communicate the working-week pattern to everyone",
               "Review employee records for gaps", "Confirm the discipline escalation line (Founder)"],
              extra=[H3("Leave process"),
                     *Flow(["Employee requests<br/>(≥1 day notice; same day<br/>only for emergencies)", "TL / Head checks<br/>project impact, approves",
                            "HR logs leave,<br/>updates balance", "HR flags coverage gap<br/>to relevant TL"], per_row=4),
                     H3("Onboarding and exit"),
                     *T([["New employee", "Departing employee"],
                         ["Company introduction and business-model walkthrough on Day 1<br/>Confirm reporting manager; set up Drive, Sheets, WhatsApp access<br/>Track first-week and first-month review dates",
                          "Confirm all active work has a new owner<br/>Coordinate access and password recovery<br/>Final documentation and clearance"]], [0.5, 0.5])]),

        *H2("Internal Content Team"),
        P("Described only in the Handbook (§06, §29). There is no brief and no incentive entry for it. It markets Brandstro itself (Instagram behind-the-scenes, "
          "reels, portfolio, case studies, campaigns, lead-generation experiments) and is judged on consistency and brand-building, not client sign-off."),
        *T([["Creative Head ensures", "Content Team Leader owns"],
            ["A content calendar exists and is followed<br/>Direction stays consistent with the agency brand<br/>Case studies get made from finished client work<br/>QC before anything publishes",
             "Shoot planning and editing workflow<br/>Day-to-day posting and scheduling<br/>The approval process before publishing"]], [0.5, 0.5]),
    ]


def ch_rules():
    return [
        *H1("Company-Wide Rules & Standards", "Chapter 8",
            "Rules that apply across roles. Most of these become validations, required fields or automated alerts in the ERP."),
        H2("8.1 The client communication rule"),
        P("Designers, R&D and the Sketch Artist do <b>not</b> talk to clients directly unless the CRM or Founder explicitly authorises it for one limited purpose. "
          "Any exception is logged. The rule exists to stop conflicting information, unapproved promises and missed instructions [CRM]. The Creative Head also "
          "should not take over day-to-day client contact; they join only when a client is unhappy after multiple rounds or there is a major escalation [Handbook §19]."),
        H2("8.2 Response-time SLAs"),
        *T([["Channel", "Standard response time"],
            ["WhatsApp: active client project", "Within 4 business hours"], ["WhatsApp: general enquiry", "Within 1 business day"],
            ["Email", "Within 1 business day"], ["Submission acknowledgement", "Same business day as receipt from production"],
            ["Stalled thread / pending approval", "Flag to Creative Head after 3+ days unresolved; send the client an update after 3+ days of silence"]], [0.45, 0.55]),
        H2("8.3 Correction or scope change?"),
        *T([["Within scope: CRM handles", "Scope change: escalate first"],
            ["Refining an agreed direction (colour, spacing, wording)", "A completely different concept after one was approved"],
            ["Fixing an error in the delivered work", "A new deliverable not in the original package"],
            ["A revision round already included in the package", "Revisions beyond the included round count"]], [0.5, 0.5], head_color=TEAL),
        P("<b>Never agree to a scope change on the spot.</b> Escalate to Sales/Founder with the request and package details, then tell the client the decision [CRM]. "
          "Handbook §25 adds a second distinction for every revision: a <b>genuine design miss</b> (fix the thinking) vs <b>subjective client preference</b> "
          "(fix the brief-gathering)."),
        H2("8.4 The correction loop"),
        *Flow(["Receive feedback", "Document it", "Is it clear?<br/>(if not, ask client)", "Scope check", "Assign to team",
               "Designer corrects", "TL reviews", "CRM resubmits", "Client approves"], per_row=5),
        H2("8.5 Client complaints"),
        *Flow(["Receive", "Categorise", "Inform team", "Root cause", "Resolve &amp; log"], per_row=5),
        P("<b>Categories:</b> Delay · Quality · Communication · Scope · Pricing/Payment · Revision · Delivery. "
          "<b>Refund, contract dispute or reputational risk?</b> Escalate to the Founder before responding [CRM]."),
        H2("8.6 Escalation ladder"),
        *T([["Level", "Handled by", "Typical examples"],
            ["1: Team-level", "Team Leader", "Second revision pass, missed internal deadline, one overloaded designer, quality issue at review"],
            ["2: Cross-team or repeated", "Creative Head", "The same handoff keeps breaking; the same designer's issue 2+ times; whole team overloaded; client deadline at risk; P1 approval"],
            ["3: Major business / people / client", "Founder", "Client threatens to leave or wants a refund; scope/pricing change; payment unresolved after one cycle; serious conduct; formal warnings"]],
          [0.22, 0.18, 0.6]),
        *Callout("Watch out: different level numbers",
                 "The Handbook uses 3 levels (TL = 1, Creative Head = 2, Founder = 3). The TL briefs call TL 'L2' and Creative Head 'L3'. The CRM brief calls "
                 "CRM 'L3' and Founder 'L4'. Same chain, different numbering. The ERP should use named levels (Team / Department / Founder), not numbers.", RED),
        H2("8.7 WhatsApp vs. the system of record"),
        *T([["Happens in WhatsApp", "Must also be logged in"],
            ["Client contact info and meeting notifications", "Client Database"], ["Fast client clarification", "Client Database: feedback log entry"],
            ["Any status or deadline change", "Project Tracker"]], [0.5, 0.5]),
        P("<b>'If it isn't also in the Sheet, it's treated as if it never happened: for scope, deadlines and approvals alike.'</b> [CRM]"),
        H2("8.8 Files, naming and versions"),
        *T([["Team", "Pattern", "Example"],
            ["Logo", "ClientName_Logo_Version_Date", "FiltersAndFlavours_Logo_v2_2026-09-06"],
            ["Packaging", "ClientName_DeliverableType_Version_Date", "Chaivanth_BrandGuidelines_v3_2026-09-06"]], [0.15, 0.4, 0.45]),
        *B(["Never overwrite a previous version. Increment v1, v2, v3.", "Working files stay in the designer's working folder and never go directly to a client.",
            "Only the TL-approved final version goes into <b>08_Final Files</b>. Research briefs live in <b>02_R&D</b>. Other numbered folders (01, 03–07) are implied but not listed."]),
        H2("8.9 Quality checklists"),
        *T([["Logo QC (TL + designer)", "Packaging / print-readiness QC (TL + designer)"],
            ["1 Concept originality and relevance to the brief<br/>2 Typography quality and appropriateness<br/>3 Alignment and proportion<br/>4 Scalability (small and large) + works in black and white<br/>5 Colour accuracy and meaning<br/>6 Presentation quality and correct file exports",
             "1 Brand consistency with approved identity<br/>2 Product / information hierarchy<br/>3 Typography and layout<br/>4 Information accuracy (no factual/spec errors)<br/>5 Correct dimensions for product/material<br/>6 Bleed and safe area applied correctly<br/>7 Mockup quality suitable for client<br/>8 Final artwork print-ready (CMYK, resolution)"]],
          [0.5, 0.5]),
        P("The Handbook adds a <b>7-point Creative Review</b> before any client presentation: Strategy, Concept, Design, Brand Fit, Distinctiveness, Application, "
          "Technical Quality (§28), and an 8-dimension quality lens (§23). See Chapter 10."),
        H2("8.10 Working time, attendance and leave"),
        *B(["Attendance is logged daily in the Attendance/HR sheet.",
            "Working week: '5 days — 2nd and 4th Saturdays off, all Sundays off' [HR]. In practice this reads as Monday–Saturday with alternate Saturdays off (see Chapter 13).",
            "Late arrivals and early departures are logged with a reason. Patterns go to the Founder monthly.",
            "Discipline: first instance, note it. A repeating pattern, escalate. HR never issues warnings without the Founder knowing."]),
    ]


def ch_incentive():
    return [
        *H1("The Performance Incentive Plan", "Chapter 9",
            "Base salary is never reduced. On top of it, each person earns a bonus for work beyond their own monthly baseline, paid at a higher "
            "rate for clean work (0–1 client revisions)."),
        H2("How it works"),
        *B(["<b>Baseline</b>: a number of projects each month that is 'just part of the job'. No bonus, no penalty.",
            "<b>Beyond baseline</b>: real money per project, with the rate set by the <b>revision tier</b>: 0–1 revisions (full), 2–3 (half), 4+ (zero; for logos, "
            "unless flagged as a client scope change).",
            "<b>Individual, not shared</b>: one person's slow month doesn't wipe out anyone else's bonus. There is no cap on the upside.",
            "<b>Team Leaders</b>: 70% of bonus from the team hitting its target, 30% from their own design work.",
            "<b>Quality-tier roles</b> (Sketch Artist, HR): a flat monthly bonus by percentage band."]),
        H2("Per-role rules (recalculated)"),
        *T([["Role", "Baseline", "Target", "Bonus rule", "Worked example → earning"],
            ["R&D", "18 concepts", "24 concepts", "Per concept beyond baseline: ₹350 (0–1 rev), ₹175 (2–3), ₹0 (4+), judged on the downstream design's revisions",
             "5 clean + 1 partial = ₹1,925 → ₹11,925 (plan rounds to ₹12,000)"],
            ["Sketch Artist", "—", "24 sketches (full capacity)", "% of sketches the Logo Team completes with no rework: ≥90% ₹5,000 · 75–89% ₹3,000 · 60–74% ₹1,500 · below 60% ₹0",
             "22/24 = 91% → ₹15,000"],
            ["Logo Designer (×3)", "4 logos", "7 logos", "Per logo beyond baseline: ₹1,650 (0–1), ₹825 (2–3), ₹0 (4+ unless scope change)",
             "3 clean = ₹4,950 → ₹14,950 (≈ ₹15,000)"],
            ["Logo Team Leader", "Personal 2 logos", "Team 21 logos + personal 4", "Team (70%): up to ₹3,500 if all 3 designers hit 7 with healthy revision rate. Personal (30%): ₹750 per clean logo beyond 2, max ₹1,500",
             "₹3,500 + ₹1,500 → ₹17,000"],
            ["Packaging Designer (×3)", "1 branding set, 1 label, 1 pack", "5 branding, 4 labels, 2 packs", "Beyond each baseline: Branding ₹700/350/0 · Label ₹450/225/0 · Packaging ₹900/450/0",
             "2,800 + 1,350 + 900 = ₹5,050 → base + ~5,000"],
            ["Packaging Team Leader", "Personal small baseline", "Team 15 branding + 12 label + 6 pack; personal 1 + 3 + 2", "Team (70%) up to ₹3,500; personal (30%) up to ₹1,500",
             "₹17,000"],
            ["CRM", "—", "42 of ~47 projects", "₹240 per project closed with 0–1 revisions <b>and</b> full 50/50 payment collected on time",
             "42 × 240 = ₹10,080 → ₹20,080 (≈ ₹20,000)"],
            ["HR / PA", "—", "11 of 12 team members hit their own target", "11–12: ₹5,000 · 9–10: ₹3,000 · 7–8: ₹1,500 · below 7: ₹0", "→ ₹15,000"]],
          [0.14, 0.12, 0.15, 0.34, 0.25], font_size=7.6),
        H2("Does the capacity add up?"),
        *T([["Output", "Company target", "Covered by", "Check"],
            ["Sketches", "24", "Sketch Artist 24", "Exactly at capacity. No slack."],
            ["Logos (logo-only + branding)", "24", "3 designers × 7 + TL 4 = 25", "OK (+1 spare)"],
            ["Branding collateral sets", "16", "3 × 5 + TL 1 = 16", "Exact"],
            ["Standalone labels", "15", "3 × 4 + TL 3 = 15", "Exact"],
            ["Standalone packaging", "8", "3 × 2 + TL 2 = 8", "Exact"],
            ["CRM clean closes", "~47 projects", "42 target", "Allows ~5 slips"]], [0.3, 0.17, 0.3, 0.23]),
        H2("Company economics at full target"),
        *T([["Line item", "Amount"],
            ["Revenue (8 logo, 16 branding, 15 label, 8 packaging)", "₹3,53,500"],
            ["Fixed payroll", "− ₹1,26,000"],
            ["Bonus payout, everyone at target", "− ₹61,900"],
            ["Rent, software, electricity, misc.", "− ₹17,000"],
            ["<b>Company profit</b>", "<b>₹1,48,600 (42.0% margin)</b>"]], [0.7, 0.3]),
        P("Recomputing the bonuses from the per-role examples gives ₹62,005 (R&D 1,925 + Sketch 5,000 + Logo 3 × 4,950 + Logo TL 5,000 + Packaging 3 × 5,050 + "
          "Pack TL 5,000 + CRM 10,080 + HR 5,000), within ₹105 of the plan's ₹61,900. The difference is rounding in the plan. The ERP should compute the exact figures.", "small"),
        H2("Monthly procedure (from the plan)"),
        *Flow(["TLs log each completion<br/>against the person<br/>+ revision count", "CRM confirms<br/>50% + 50% payment<br/>per project",
               "Month-end: tally each<br/>person vs own target<br/>and revision tier", "TLs: team 70% and<br/>personal 30%<br/>checked separately",
               "Pay base + bonus<br/>in same payroll cycle"], per_row=5),
        *Callout("ERP note: data the incentive engine needs",
                 ["Per completed deliverable: the <b>credited person</b>, deliverable type (logo / branding set / label / packaging / R&D concept / sketch), completion date, "
                  "<b>client revision count</b>, whether revisions were flagged as <b>client scope change</b>, 'needed rework' flag (for Sketch), and payment status.",
                  "Per person per month: baseline and target per work type, rate table by tier, role formula (per-unit, tiered %, or 70/30 team split). All configurable, never hard-coded."], TEAL),
    ]
