"""Chapters 10-15: leadership system, tools, ERP blueprint, gaps, glossary, appendix index."""
from kit import P, H1, H2, H3, B, T, Callout, Flow, TEAL, RED, ACCENT, GREEN


def ch_leadership():
    return [
        *H1("The Creative Head's Management System", "Chapter 10",
            "The 70-page Handbook, condensed. It is a coaching curriculum (read section by section with the Founder), but it also defines "
            "the reviews, metrics, meetings and scorecards the ERP should make easy."),
        H2("Structure of the Handbook"),
        *T([["Part", "Sections", "Theme"],
            ["1 The Role", "01–06", "From performer to multiplier; mission; what the role is NOT; authority layers; the agency's teams"],
            ["2 Leading the Leaders", "07–16", "Weekly TL review, performance framework, underperformance, problem-solving, conflict, delegation, feedback, culture"],
            ["3 Running the Department", "17–22", "Capacity and workload, cross-team handoffs, client involvement, QC, training, leadership pipeline"],
            ["4 Branding-Agency Leadership", "23–30", "Judging creative quality, the 8-stage process, revision management, briefs, creative review, content team, dashboard"],
            ["5 Operating Discipline", "31–41", "Daily/weekly/monthly rhythm, meetings, decisions, escalation, accountability, EQ, mistakes, systems"],
            ["6 First 90 Days", "42", "Understand (1–30) → Improve (31–60) → Scale (61–90)"],
            ["7 Practice", "43–45", "16 real office scenarios, self-reflection questions, 13-category scorecard"],
            ["8 Partnership", "46–49", "Founder relationship, success definition, 20 principles, signed commitment"]], [0.22, 0.1, 0.68]),
        P("Each Part ends with discussion pages (Founder's notes, Creative Head's notes, key agreements, action items with owner / deadline / review date)."),

        *H2("Weekly Team Leader Review: 8 questions (§07)"),
        *T([["Area", "Question"],
            ["Output", "What did your team finish this week, and what's still open?"], ["Quality", "What needed rework, and why?"],
            ["Deadlines", "What's at risk in the next seven days?"], ["Client blockers", "What's waiting on a client response or approval?"],
            ["Discipline & morale", "Anything you're worried about with a specific person?"], ["Bottlenecks", "Where did work sit idle, and why?"],
            ["Resourcing", "Do you have enough people for what's coming next week?"], ["Improvement action", "What's one thing you'll do differently next week?"]],
          [0.25, 0.75]),
        *H2("Performance framework (§08–09)"),
        P("<b>Nine dimensions:</b> output, quality, timeliness, consistency, efficiency, improvement, accountability, collaboration, problem-solving. "
          "<b>Scorecard KPIs:</b> tasks assigned vs completed, on-time completion %, revision rounds per project, rework hours, escalations, client-facing errors. "
          "KPIs are for spotting where coaching is needed, not for catching people out."),
        P("<b>Underperformance in 8 steps:</b> Identify → Measure → Diagnose → Coach → Improvement plan → Timeline → Review → Escalate. "
          "Causes to check: workload, skill gap, unclear brief or standard, lack of training, poor management above, personal issues, process problem, wrong role."),
        *H2("Problem-solving and conflict (§10–11)"),
        P("Use the <b>5 Whys</b> to find the root cause. The Handbook's example: a packaging job was 3 days late because the designer waited on R&D, "
          "R&D wasn't told it was urgent, and there was no shared deadline view. Root cause: <b>no one owns a visible cross-team tracker</b>. "
          "Record: Problem → Cause → Solution → Owner → Deadline → Review."),
        P("<b>Conflict path:</b> Listen → Understand → Separate facts from feelings → Root cause → Decide → Communicate → Follow up. Praise publicly, correct privately."),
        *H2("Delegation, communication, feedback (§12–15)"),
        *B(["Delegation record: Task, Owner, Expected result, Deadline, Authority, Checkpoint.",
            "<b>SBI</b> for feedback (Situation, Behaviour, Impact). <b>CLEAR</b> for instructions (Context, Expectation, Action, Deadline, Review).",
            "Feedback types: positive, corrective, performance, leadership, difficult."]),
        *H2("Workload and capacity tools to introduce (§17–18)"),
        *T([["Tool", "Answers"],
            ["Capacity Planning", "Given today's team, how many projects can realistically start this week?"],
            ["Workload Dashboard", "Who is overloaded, who has room, right now?"], ["Priority Matrix", "Urgent-and-important vs important-not-urgent"],
            ["Daily Task Review", "Is today's plan still realistic by lunchtime?"], ["Weekly Capacity Review", "Are we about to overcommit next week?"],
            ["Shared status view", "Project, current owner, days-to-deadline. 'Who has this right now' should never need asking."]], [0.3, 0.7]),
        *H2("Creative quality lens (§23) and 7-point review (§28)"),
        *T([["Quality dimension (§23)", "Ask"],
            ["Concept strength", "A real idea, or just decoration?"], ["Strategic relevance", "Fits the brand's positioning?"],
            ["Distinctiveness", "Stands out next to five competitors?"], ["Simplicity & memorability", "Describable after one look?"],
            ["Scalability", "Works as a favicon and a shopfront sign?"], ["Typography & colour", "Deliberate or default?"],
            ["Application", "Works on packaging, stationery, t-shirt?"], ["Technical execution", "Production-ready file?"]], [0.35, 0.65]),
        P("7-point pre-presentation review: <b>Strategy · Concept · Design · Brand Fit · Distinctiveness · Application · Technical Quality</b>."),
        *H2("Revision management (§25) and brief quality (§27)"),
        *B(["Track four things: revision rate by project type, first-presentation approval share, revision root cause (design miss vs preference), recurring client feedback patterns.",
            "Current pattern: some clients approve the first draft; 'fine' clients need about 2 corrections; a few need 3+; very few need 5+.",
            "The ₹15,000 branding package has sold with <b>informally unlimited revisions</b> for some clients. That is a margin problem: 5 rounds consume time priced for 2.",
            "<b>Briefing checklist:</b> brand in one sentence, target audience, positioning, business objective, what to communicate/avoid, competitors, "
            "exact deliverables and deadline, what the client expects to see first, reference direction / constraints. Missing items are flagged [CLIENT INPUT REQUIRED]."]),
        *H2("Performance dashboard (§30)"),
        *T([["Area", "Track"],
            ["Production", "Projects received, completed, in progress, pending, delayed"],
            ["Logo / Identity", "Concepts completed, first-presentation quality, revision rounds, turnaround time"],
            ["Packaging", "Concepts completed, revision rounds, turnaround time, technical errors caught"],
            ["R&D", "Concepts/research delivered, support requests, turnaround time"],
            ["Internal Content", "Content planned vs produced vs published, pending items"],
            ["People", "Attendance, productivity, training progress, leadership development"]], [0.25, 0.75]),
        *H2("Operating rhythm and meetings (§31–32)"),
        *T([["Meeting", "Length", "Purpose"],
            ["Daily leadership check-in", "10–15 min", "Surface today's risks"], ["Weekly Team Leader meeting", "30–45 min", "The 8-question review"],
            ["Monthly department review", "60 min", "Trends, scorecard, next month's priorities"], ["One-to-one employee review", "15–20 min", "Individual development"],
            ["Performance improvement meeting", "As needed", "§09 framework"], ["Problem-solving meeting", "As needed", "§10 framework"],
            ["Post-project review", "15 min", "What worked / didn't on a finished project"]], [0.38, 0.15, 0.47]),
        P("Every meeting ends with action items that have an owner and a date. 'A meeting without an action item was a conversation, not a decision.'"),
        *H2("Decisions, mistakes, accountability (§33–41)"),
        *B(["<b>Decide alone</b> when it's within one team, reversible, and within authority. <b>Consult TLs</b> when it changes how a team works or sets a precedent. "
            "<b>Founder</b> when it changes pricing, scope, a client relationship, hiring/firing, major spend, or involves serious repeated people problems.",
            "Accountability record: What? Who? When? Expected standard? Current status? Next action?",
            "Mistake types and responses: honest (fix, note the pattern), repeated negligence (documented conversation), skill gap (training), "
            "attention gap (find the cause), intentional misconduct (Founder).",
            "Recurring problem → build a system (checklist, dashboard, approval step, training module, escalation rule)."]),
        *H2("30 / 60 / 90 days (§42)"),
        *T([["Days 1–30: Understand", "Days 31–60: Improve", "Days 61–90: Scale"],
            ["Learn how work flows across all four teams<br/>Sit with each TL<br/>Map problems (start with Packaging)<br/>Set baseline KPIs",
             "Fix top problems<br/>Start structured TL coaching<br/>Introduce weekly review and shared status view<br/>Close the missing client sign-off step",
             "Standardise what worked<br/>First leadership pipeline<br/>Sustainable daily/weekly/monthly rhythm<br/>Report changes to Founder with numbers"]],
          [0.333, 0.333, 0.334]),
        *H2("16 real scenarios (§43), in short"),
        *T([["#", "Situation", "Strong move"],
            ["1", "Packaging misses another deadline", "Run 5 Whys with the TL; fix capacity, handoff or skill, not just this project"],
            ["2", "Designer argues with TL in public", "Separate them, hear both privately, coach the TL on de-escalation"],
            ["3", "TL great at craft, poor with people", "Name it; coach specific leadership behaviours"],
            ["4", "One designer far outperforms", "Recognise; learn what they do differently; don't overload them"],
            ["5", "Talented but undisciplined designer", "Same standard as everyone"],
            ["6", "Designer escalates small issues to you", "Redirect to TL; tell the TL"],
            ["7", "Client revision spike mid-project", "Check brief miss vs scope creep; involve CRM"],
            ["8", "30 clients, capacity for 6–8", "Capacity plan, realistic timelines, flag the mismatch to Founder with numbers"],
            ["9", "One team idle, another buried", "Use the shared status view to redistribute or cross-train"],
            ["10", "TL hides a team problem", "Address privately; it's about trust"],
            ["11", "Unfair workload complaint", "Check the workload dashboard before responding"],
            ["12", "High performer turns arrogant", "Address the behaviour directly"],
            ["13", "Junior shows leadership potential", "Give small ownership now"],
            ["14", "Same packaging mistake keeps recurring", "3+ times = system gap; add it to the checklist"],
            ["15", "Deadline tomorrow, work incomplete", "Assess honestly; warn client early; then assign"],
            ["16", "Founder gets a quality complaint", "Investigate; bring cause and fix, not excuses"]], [0.05, 0.4, 0.55], font_size=7.8),
        *H2("Monthly scorecard (§45)"),
        P("Rated 1–5 with the Founder: Overall team performance · Team Leader development · Productivity · Quality · Deadline management · Problem solving · "
          "Employee development · Communication · Discipline & culture · Process improvement · Cross-team coordination · Leadership pipeline · Strategic thinking. "
          "(1 = urgent attention, 3 = meeting the bar, 5 = a model for other leaders.)"),
        *Callout("How to bring problems to the Founder (§46)",
                 "Problem + Analysis + Options + Recommendation. Not just 'Packaging is behind again.'", ACCENT),
    ]


def ch_tools():
    return [
        *H1("Today's Tools → What the ERP Replaces", "Chapter 11",
            "Brandstro currently runs on Google Drive, Google Sheets and WhatsApp. These are the tools the documents mention, and what each becomes."),
        *T([["Current tool", "Used by", "Holds", "Becomes in the ERP"],
            ["WhatsApp: Leads group", "Founder, CRM", "Incoming enquiries", "Leads module (optionally WhatsApp Business API intake)"],
            ["WhatsApp: Client Meetings group", "CRM, team", "Meeting notifications, quick clarifications", "Meeting scheduler + client communication log; WhatsApp stays as a notification channel"],
            ["Client Database (sheet)", "CRM", "Client info, feedback log", "Clients, Contacts, Feedback entities"],
            ["Project Tracker (sheet)", "All", "Status, deadlines, handoffs, timestamps, revisions", "Projects / Deliverables / Stage history (auto-timestamped)"],
            ["Team Task Tracker (sheet)", "TLs, designers", "Assignments, load, deadlines", "Task board + workload view per designer"],
            ["QC checklist logs", "TLs, designers", "Review outcomes", "Checklist records attached to each review"],
            ["Attendance / HR sheet", "HR", "Attendance, leave balances", "HR module: attendance, leave, holiday calendar"],
            ["Google Drive project folders (02_R&D … 08_Final Files)", "All", "Briefs, working files, finals", "Keep Drive for files; ERP stores links, versions and enforces naming"],
            ["Sales handover notes", "Founder → CRM", "Package, price, promises", "Order record with a required handover section"],
            ["Monthly review packs", "Founder, Creative Head", "Summaries, scorecards", "Generated dashboards and reports"]],
          [0.23, 0.14, 0.25, 0.38], font_size=8),
        *Callout("Recommendation",
                 "Don't try to replace Drive file storage or WhatsApp chat. Replace the <b>sheets</b> and connect to the other two: store Drive links and "
                 "versions, and send WhatsApp/email notifications from the ERP. That matches the rule 'WhatsApp for speed, the sheet for the record'.", GREEN),
    ]


def ch_erp():
    return [
        *H1("ERP Blueprint", "Chapter 12",
            "A proposed design derived from the documents. Everything here traces back to a rule in Chapters 4–10. "
            "Where the documents are silent, the choice is marked as a recommendation."),
        H2("12.1 Modules"),
        *T([["#", "Module", "Covers", "Primary users"],
            ["1", "Sales & Leads", "Leads, quotes, orders, packages sold, handover notes", "Founder"],
            ["2", "Clients (CRM)", "Client database, contacts, onboarding checklist, discovery notes, communication log, SLA timers", "CRM"],
            ["3", "Projects & Workflow", "Projects, deliverables, route (with/without sketch), stage transitions, handoff acknowledgement", "All"],
            ["4", "Briefs", "Project Brief (CRM), briefing checklist with [CLIENT INPUT REQUIRED] flags, R&D research brief template", "CRM, R&D"],
            ["5", "Queues & Assignment", "R&D and Sketch queues (P1/P2/P3, FIFO by payment date), TL assignment by load", "R&D, Sketch, TLs"],
            ["6", "Design Production", "Tasks, file versions (Drive links), naming validation, mockups", "Designers, TLs"],
            ["7", "Quality Control", "Logo QC, Packaging/print QC, Sketch self-check, 7-point creative review; pass/rework log", "TLs, Creative Head"],
            ["8", "Feedback, Revisions & Approvals", "Feedback log, revision rounds, scope classification, scope-change approval, client sign-off", "CRM, TLs, Founder"],
            ["9", "Complaints", "Categorised complaints, root cause, resolution, escalation", "CRM, Founder"],
            ["10", "Billing & Payments", "Advance/final invoices, receipts, follow-ups, release gate for final files", "CRM, HR/Accounts, Founder"],
            ["11", "HR", "Employees, attendance, leave, discipline log, onboarding/exit checklists, work calendar", "HR"],
            ["12", "Performance & Incentives", "Targets, baselines, rate tables, completions, monthly bonus calculation, payroll export", "Founder, HR"],
            ["13", "Leadership & Reviews", "Weekly TL review form, action items, improvement plans, 1:1s, monthly scorecard, 90-day plan", "Creative Head, Founder"],
            ["14", "Dashboards & Reports", "Department dashboard, capacity/workload, SLA, revision analytics, profitability", "Founder, Creative Head, TLs"],
            ["15", "Internal Content", "Content calendar, planned/produced/published, approvals, case-study pipeline", "Content TL, Creative Head"],
            ["16", "Notifications", "WhatsApp/email/in-app alerts, escalation rules", "System"]], [0.04, 0.2, 0.56, 0.2], font_size=8),

        H2("12.2 Core entities and key fields"),
        *T([["Entity", "Key fields"],
            ["Employee", "name, role, team, reports_to, base_salary, join_date, status, access flags"],
            ["Team", "name (Logo / Packaging / R&D-Sketch / Content), leader_id"],
            ["Product / Package", "name, base_price, additional_unit_price, included_deliverables[], included_revision_rounds, route_template"],
            ["Lead", "source, contact, interest, status, owner (Founder)"],
            ["Client", "business name, contacts, industry, onboarding checklist state, notes"],
            ["Order", "client, package(s), agreed price, discount, promises_made, handover_notes, sold_by, sold_on"],
            ["Invoice / Payment", "order, milestone (advance / final), amount, due_date, paid_on, follow_up_count"],
            ["Project", "order, route (with sketch / direct / designer-originated), priority P1/P2/P3, payment_confirmed_on (queue order), client_deadline, current_stage, current_owner, crm_owner"],
            ["Deliverable", "project, type (logo, guideline book, visiting card, letterhead, t-shirt, label, packaging), team, assignee, status, revision_count, internal_rework_count, credited_to"],
            ["Brief", "project, type (project brief / research brief), sections (6-part template), missing_inputs[], file_link, completed_on"],
            ["Handoff", "project, from_owner, to_owner, sent_at, acknowledged_at"],
            ["File Version", "deliverable, version_no, file_name (validated), drive_link, is_final, approved_by"],
            ["QC Review", "deliverable, checklist_type, item results, outcome (pass / rework), reviewer, reviewed_at"],
            ["Client Feedback", "deliverable, received_at, channel, text, is_clear, classification (in-scope / scope change), root cause (design miss / preference), round_no"],
            ["Scope Change Request", "project, description, escalated_to, decision, price_change, decided_at"],
            ["Approval / Sign-off", "deliverable or project, approved_by_client_at, evidence (message/screenshot link)"],
            ["Complaint", "client, project, category (7), severity, root cause, resolution, escalated flag"],
            ["Attendance / Leave", "employee, date, status, in/out, late reason; leave type, dates, approver, balance"],
            ["Discipline Note", "employee, date, type, pattern_flag, founder_informed"],
            ["Incentive Plan", "role, period, baselines per work type, target, rate table by revision tier, formula type (per-unit / tiered % / team 70-30)"],
            ["Monthly Incentive Result", "employee, month, counts per tier, bonus, approved_by, paid_in_payroll"],
            ["Action Item", "source meeting/review, description, owner, deadline, review_date, status"]], [0.2, 0.8], font_size=8),

        H2("12.3 Deliverable status workflow"),
        P("Recommendation: track status on each <b>deliverable</b>, and derive the project's status from them. A branding package has a logo in the Logo Team and "
          "four or five collateral pieces in the Packaging Team at once, so one project-level status can't show where the work actually is."),
        *Flow(["Awaiting advance", "Discovery", "Brief ready", "R&amp;D queue", "R&amp;D in progress",
               "Sketch queue*", "Sketching*", "Awaiting assignment", "In design", "TL review",
               "Ready for client", "With client", "Feedback received", "In correction", "Client approved",
               "Awaiting final payment", "Final files delivered", "Closed"], per_row=5),
        P("* Only for routes that use the sketch step. Side states: <b>Rework</b> (TL review failed → back to In design), <b>Scope change pending</b> "
          "(feedback classified as scope change → Founder decision), <b>On hold</b> (waiting on client input), <b>Cancelled</b>.", "small"),
        H3("Transition rules (guards)"),
        *T([["Transition", "Allowed only if", "Source"],
            ["→ R&D queue", "Advance payment recorded; brief has no unresolved [CLIENT INPUT REQUIRED] (or override logged)", "[CRM][R&D][Handbook §27]"],
            ["R&D → next stage", "Research brief complete (all 6 sections) + file in 02_R&D + next owner acknowledged", "[R&D]"],
            ["→ Ready for client", "QC review with outcome = pass by the team's TL", "[LogoTL][PackTL]"],
            ["→ With client", "Performed by CRM only", "[CRM]"],
            ["Feedback → In correction", "Classified as in-scope and revision round ≤ package limit; otherwise → Scope change pending", "[CRM]"],
            ["In correction → Ready for client", "TL re-review passed (packaging: fresh print-readiness check if dimensions/bleed/artwork changed)", "[PackDes][PackTL]"],
            ["→ Client approved", "Sign-off evidence recorded", "[CRM]"],
            ["→ Final files delivered", "Final payment recorded; file marked final and in 08_Final Files", "[Handbook §24][LogoDes]"],
            ["P1 priority set", "Approved by Founder/Creative Head; no other P1 active in that queue", "[R&D]"]], [0.25, 0.57, 0.18], font_size=8),

        H2("12.4 Roles and permissions (summary)"),
        *T([["Capability", "Founder", "Creative Head", "CRM", "TL", "Designer", "R&D / Sketch", "HR"],
            ["Create leads/orders, set price and discount", "Yes", "—", "View", "—", "—", "—", "—"],
            ["Client database and client messages", "Yes", "View", "Yes", "View", "—", "—", "—"],
            ["Set priority P1", "Yes", "Yes", "Request", "—", "—", "—", "—"],
            ["Assign work within team", "—", "Yes", "—", "Own team", "—", "—", "—"],
            ["Upload versions / submit to TL", "—", "—", "—", "Yes", "Yes", "Yes", "—"],
            ["QC pass / rework", "—", "Yes", "—", "Own team", "—", "—", "—"],
            ["Submit to client, log feedback, sign-off", "Yes", "—", "Yes", "—", "—", "—", "—"],
            ["Approve scope change / extra revisions", "Yes", "Extra revisions", "Escalate", "Escalate", "—", "—", "—"],
            ["Record payments", "Yes", "—", "Yes", "—", "—", "—", "Accounts"],
            ["Attendance and leave", "View all", "View", "Self", "Approve team", "Self", "Self", "Manage"],
            ["Discipline notes / warnings", "Issue", "View", "—", "—", "—", "—", "Log only"],
            ["Incentive results", "Approve", "View dept", "Self", "Team + self", "Self", "Self", "Prepare"]],
          [0.28, 0.1, 0.11, 0.09, 0.1, 0.1, 0.12, 0.1], font_size=7.4),

        H2("12.5 Automations and alerts"),
        *T([["Trigger", "Action", "Source rule"],
            ["Client message on active project unanswered 4 business hours (1 day for enquiry/email)", "Alert CRM; SLA breach logged", "[CRM] SLAs"],
            ["Production marks 'Ready for client' and no submission by end of day", "Alert CRM", "[CRM] same-day acknowledgement"],
            ["Client thread silent or approval pending 3+ days", "Prompt CRM to send update; weekly flag to Creative Head", "[CRM]"],
            ["Handoff not acknowledged within X hours", "Alert sender and receiver; stage treated as not started", "[R&D]"],
            ["Days-to-deadline below threshold and stage not advanced", "Deadline-risk flag on dashboard; notify TL, then Creative Head", "[Handbook §18][LogoTL]"],
            ["Revision round exceeds package limit", "Block auto-assignment; require scope decision", "[CRM][Handbook §25]"],
            ["Same designer fails QC 2+ times on the same issue", "Escalate to Creative Head", "[LogoTL][PackTL]"],
            ["Same QC failure item 3+ times across the team", "Suggest adding to the checklist (system gap)", "[Handbook §43 #14]"],
            ["Final payment outstanding after one follow-up cycle", "Escalate to Founder", "[CRM]"],
            ["Unapproved absence", "Same-day flag to HR and TL; repeat → Founder", "[HR]"],
            ["Leave approved during active deadlines", "Coverage-gap alert to TL", "[HR]"],
            ["Designer queue much longer than peers", "Rebalance suggestion to TL", "[LogoTL][PackTL]"],
            ["Month end", "Compute incentive results for approval", "[Incentive]"]], [0.45, 0.35, 0.2], font_size=8),

        H2("12.6 Dashboards"),
        *B(["<b>Founder:</b> sales vs 47-engagement target by product, revenue, receivables, margin estimate, escalations, complaints.",
            "<b>Creative Head:</b> §30 dashboard (production, per-team metrics, people), capacity vs demand for next week, deadline-risk list, first-presentation approval rate, revision root causes.",
            "<b>Team Leader:</b> designer workload, QC pass rate, overdue items, team progress to monthly target (the 70% component).",
            "<b>CRM:</b> open threads with SLA clocks, pending approvals, payments due, clean-close count toward 42.",
            "<b>Individual:</b> my queue, my deadlines, my progress to baseline and target, my projected bonus.",
            "<b>HR:</b> attendance today, leave calendar, coverage gaps, team members on track for target (HR bonus metric)."]),

        H2("12.7 Incentive engine formulas"),
        *T([["Formula type", "Roles", "Calculation"],
            ["Per-unit, tiered by revisions", "R&D, Logo Designer, Packaging Designer",
             "For each work type: units beyond baseline, taken in completion order → rate[tier(revisions)]. Tier: 0–1 full · 2–3 half · 4+ zero "
             "(logo 4+ counts as full or half if flagged as client scope change; the rule needs confirming). Sum over work types."],
            ["Quality band", "Sketch Artist", "pct = sketches with no rework ÷ sketches delivered → band bonus (90/75/60)"],
            ["Team 70 / personal 30", "Logo TL, Packaging TL", "team_part = 3,500 if every designer hits target and team revision rate is 'healthy' (threshold needs defining); personal_part = rate × clean units beyond personal baseline, capped at 1,500"],
            ["Per clean close", "CRM", "240 × projects with ≤1 revision AND both payments collected on time"],
            ["Team attainment band", "HR / PA", "count of the 12 who hit their own target → band bonus (11/9/7)"]], [0.2, 0.22, 0.58], font_size=8),
        *Callout("Question the engine must settle",
                 "Which units count as 'beyond baseline' when a person completes, say, 7 logos with mixed revision counts? The plan's examples assume the extra ones are the clean ones. "
                 "Recommendation: count in completion order and show the rule on each person's dashboard so nobody is surprised.", RED),

        H2("12.8 Suggested build phases"),
        *T([["Phase", "Scope", "Why first"],
            ["1: Core record (4–6 weeks)", "Employees/roles, clients, orders, projects/deliverables, stage workflow, handoffs, Drive links, file naming, basic dashboard",
             "Replaces the Project Tracker, the most-referenced tool. Answers 'who has this right now?'"],
            ["2: Quality and client loop", "QC checklists, feedback log, revision counting, scope-change approval, sign-off, SLA timers, payments with release gate",
             "Produces the revision and payment data the incentives depend on"],
            ["3: People and money", "Attendance, leave, discipline, incentive engine, payroll export", "Needs 1 month of clean phase-2 data to be trustworthy"],
            ["4: Leadership layer", "Weekly TL review forms, action items, scorecards, capacity planning, revision analytics, content calendar", "Turns the Handbook into routine"]],
          [0.22, 0.5, 0.28]),
    ]


def ch_gaps():
    rows = [["#", "Issue", "Where", "Why it matters for the ERP / question for the Founder"],
            ["1", "Master SOP referenced (sections 6–38) but not provided", "All briefs", "May define packages, revision limits, folders, payment terms. Ask for it."],
            ["2", "Logo Team size: 4 designers vs 3", "LogoTL vs Incentive", "Capacity, targets and payroll change. Confirm the real headcount."],
            ["3", "Creative Head not in payroll, bonus plan or profit maths", "Incentive vs Handbook", "Is the Creative Head a separate salary (profit falls) or combined with a TL role?"],
            ["4", "Internal Content Team has no brief, no headcount, no incentive", "Handbook only", "Is it staffed? Should the ERP include the content module now?"],
            ["5", "Included revision rounds per package never stated; branding 'informally unlimited' for some", "CRM vs Handbook §25", "Needed to detect scope creep automatically. Define N per package."],
            ["6", "Label/Packaging price '(1st)': price for additional units unknown", "Incentive", "Needed for quoting and invoices."],
            ["7", "CRM scope: brief says escalate pricing/discounts; Incentive says CRM 'closes deals' and collects payments", "CRM vs Incentive", "Can the CRM create orders or change prices? Sets permissions."],
            ["8", "HR scope: brief = HR/Admin; Incentive = HR/Personal Assistant with accounts and oversight of CRM/TLs", "HR vs Incentive", "Does HR get finance and project-oversight access?"],
            ["9", "Escalation levels numbered differently (1–3, L2–L3, L3–L4)", "Handbook vs briefs", "Use named levels."],
            ["10", "Working week: '5 days' but only 2nd/4th Saturdays off; Sketch capacity assumes 24 days, Packaging maths assumes 21 days/person", "HR vs Incentive", "Define the working-day calendar once; capacity and SLAs ('business hours') depend on it."],
            ["11", "Business hours for the 4-hour SLA not defined", "CRM", "Needed to compute SLA timers."],
            ["12", "R&D benchmark 2 briefs/day (~48/month) vs incentive target 24 'concepts'", "R&D vs Incentive", "Does a 'concept' count only logo/branding briefs, or packaging research too?"],
            ["13", "Sketch step sometimes skipped / designer-originated concepts", "Handbook §18, §24", "Route must be selectable per project; who gets R&D/Sketch credit then?"],
            ["14", "Branding package: collateral in parallel with the logo, or after logo approval?", "Not stated", "Drives the workflow dependency between the two teams."],
            ["15", "'Healthy team-wide revision rate' for the TL bonus not quantified", "Incentive", "Needs a number (e.g. average ≤ 1.5 rounds)."],
            ["16", "Logo 4+ revisions pay zero 'unless flagged as client scope change'. The pay rate in that case isn't stated; other roles don't have the exception.", "Incentive", "Define the rule and who can set the flag."],
            ["17", "Who records 'no rework' for the Sketch Artist bonus", "Incentive", "Probably Logo TL. Add a field at design start."],
            ["18", "Drive folder structure only partly known (02_R&D, 08_Final Files)", "Briefs", "Need the full 01–08 list to generate folders automatically."],
            ["19", "No formal client sign-off existed before (Handbook); the CRM brief now requires it", "Handbook §24 vs CRM", "Make sign-off a mandatory step with evidence."],
            ["20", "Intake exceeded capacity (30 clients vs 6–8 done)", "Handbook §17", "Sales should see capacity before promising start dates. Add a capacity check to order creation."]]
    return [
        *H1("Gaps, Contradictions & Open Questions", "Chapter 13",
            "Places where the ten documents disagree, or where the ERP needs a rule nobody has written down yet. Settle these with the Founder "
            "before building the affected module."),
        *T(rows, [0.04, 0.34, 0.16, 0.46], font_size=7.8),
        *Callout("Suggested next step",
                 "Take this table into one 60-minute session with the Founder. Items 2, 3, 5, 7, 10 and 14 affect the data model and should be settled "
                 "before Phase 1. The rest can be settled during Phases 2–3.", GREEN),
    ]


def ch_glossary():
    return [
        *H1("Glossary & Numbers Cheat-Sheet", "Chapter 14"),
        H2("Glossary"),
        *T([["Term", "Meaning at Brandstro"],
            ["CRM", "Client Relationship Manager: the person (not software) who is the only link to clients"],
            ["TL", "Team Leader (Logo TL, Packaging TL)"], ["Creative Head", "Leader of the Team Leaders; owns department performance"],
            ["R&D", "Research & creative direction role; produces the research brief"],
            ["Research brief", "R&D's 6-section structured output: overview, audience, competitors, positioning, visual direction, include/avoid"],
            ["Project Brief", "CRM's requirement summary handed to R&D after discovery"],
            ["Concept set", "The Sketch Artist's 3–5 distinct sketch directions for one logo"],
            ["Branding package", "₹15,000 product: logo + guideline book, visiting card, letterhead, t-shirt, packaging"],
            ["Correction / revision", "A client-requested change within the agreed direction; counted in rounds"],
            ["Rework", "Internal: TL sends work back before it reaches the client"],
            ["Scope change", "New concept after approval, new deliverable, or rounds beyond the package. Founder decides."],
            ["Clean", "Completed with 0–1 client revisions (full bonus rate)"],
            ["Baseline", "Monthly units that are part of the job (no bonus)"],
            ["P1 / P2 / P3", "Queue priorities: urgent (one at a time) / standard FIFO by payment / work-ahead"],
            ["Print-ready", "Correct dimensions, bleed, safe area, CMYK, resolution"],
            ["08_Final Files", "Drive folder for TL-approved finals only"],
            ["SBI / CLEAR", "Feedback model (Situation-Behaviour-Impact) / instruction model (Context-Expectation-Action-Deadline-Review)"],
            ["Handoff", "Moving ownership to the next stage; incomplete until acknowledged"]], [0.22, 0.78]),
        H2("Numbers cheat-sheet"),
        *T([["Number", "Meaning"],
            ["₹6,000 / ₹15,000 / ₹2,500 / ₹3,500", "Logo / Branding package / Label (1st) / Packaging (1st)"],
            ["8 / 16 / 15 / 8 = 47", "Monthly sales target by product"], ["₹3,53,500", "Monthly revenue target"],
            ["50% + 50%", "Advance before work; balance before final files"], ["24", "Sketches per month (company-wide ceiling for logo + branding)"],
            ["2 / 1 / 1 / 1", "Daily benchmarks: R&D briefs / sketch sets / logos per designer / packaging designs per designer"],
            ["3–5", "Distinct sketch concepts per logo; competitor references in a research brief"],
            ["4 hrs / 1 day / same day", "CRM SLAs: active WhatsApp / enquiry & email / submission acknowledgement"],
            ["3+ days", "Stalled client thread → update client, flag to Creative Head"],
            ["2+ times", "Same designer's quality issue → escalate to Creative Head"],
            ["3+ times", "Same mistake across the team → treat as a system gap"],
            ["0–1 / 2–3 / 4+", "Revision tiers: full / half / zero bonus"], ["70 / 30", "TL bonus split: team / personal"],
            ["₹1,26,000 / ₹61,900 / ₹17,000", "Payroll / full bonus / overheads per month"], ["~42%", "Margin at full target (required 40–50%)"],
            ["1 day", "Minimum notice for planned leave"], ["2nd & 4th Saturday, all Sundays", "Days off"]], [0.35, 0.65]),
    ]


def ch_appendix(entries):
    rows = [["Original document", "Pages", "Starts on page"]] + [[n, str(c), str(s)] for n, c, s in entries]
    return [
        *H1("Appendix: Original Documents", "Part B",
            "The ten source PDFs follow, unchanged, in the order below. Each one is also bookmarked in the PDF sidebar."),
        *T(rows, [0.62, 0.13, 0.25]),
        P("Page numbers are positions in this combined file. The original documents keep their own internal page numbering.", "small"),
    ]
